name: Static Code Analysis

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pylint

      - name: Code analysis 1
        run: |
          cd OrderPayment
          pylint --disable=C0103 .

      - name: Code analysis 2
        run: |
          cd OrderPayment_Refactored
          pylint --disable=C0103 .
          